apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sergio-demo-hpa
  namespace: golo-gt
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sergio-demo
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 15
      policies:
        - type: Percent
          value: 100
          periodSeconds: 5
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 5

